	/**
	 * Dragster is a class to represent a dragster that
	 *  races at a drag strip.
	 * 
	 *  Create Dragster objects and "race" them to determine
	 *  their elapsed time for a 1/4 mile race.
	 */
	public Dragster {

	/**
	 * 
	 * See Also:
	 * Constant Field Values
	 * 
	 */
 
	/**
	 * 
	 * Parameters:
	 * reactionTime - time to react to start signal
	 * torque - power generated by the engine
	 * traction - how good the traction is
	 * burn - how many seconds to "burn out" the tires
	 * 
	 */
private int burnTime
	/**
	 * 
	 * See Also:
	 * Constant Field Values
	 * 
	 */
private double reactionTime
	/**
	 * 
	 * See Also:
	 * Constant Field Values
	 * 
	 */
private int torque
	/**
	 * 
	 * See Also:
	 * Constant Field Values
	 * 
	 */
private double TORQUE2TIME
	/**
	 * 
	 * Parameters:
	 * reactionTime - time to react to start signal
	 * torque - power generated by the engine
	 * traction - how good the traction is
	 * burn - how many seconds to "burn out" the tires
	 * 
	 */
private double traction


	/**
	 * 
	 * See Also:
	 * Constant Field Values
	 * 
	 */
	public   {
		//TODO Add method body for 
	}

	public void burnout() {
		//TODO Add method body for burnout()
	}

	public private double conditionTires(double time) {
		//TODO Add method body for conditionTires(double time)
	}

	public double race() {
		//TODO Add method body for race()
	}

	public java.lang.String toString() {
		//TODO Add method body for toString()
	}


}