/**
 * Dragster is a class to represent a dragster that
 *  races at a drag strip.
 * 
 *  Create Dragster objects and "race" them to determine
 *  their elapsed time for a 1/4 mile race.
 */
public Dragster {

	/**
	 * Private instance variable for the number of seconds to "burn out"
	 *  the tires. Typically under 10 seconds.
	 */
 	private int burnTime;

	/**
	 * Private instance variable for the time it takes the
	 *  driver to react to the "go" signal. Typical time is
	 *  around 0.5 second.
	 */
 	private double reactionTime;

	/**
	 * Private instance variable for the amount of torque (ft-lbs)
	 *  generated by the engine. Typical values are around 1000.
	 */
 	private int torque;

	/**
	 * Private constant to convert torque values to equivalent time.
	 *  Value = 5000
	 */
 	private double TORQUE2TIME;

	/**
	 * Private instance variable for the amount of traction the tires
	 *  have. Typical values for traction are between 0.5 and 1.0.
	 *  Tires are "conditioned" prior to racing by "burning out"
	 *  (squealing the tires in place) to remove a layer of oxidized
	 *  rubber and to preheat the tire. Typical burnout times are a
	 *  few seconds (under 10 seconds).
	 */
 	private double traction;



	 */
	public void burnout() {
		//TODO Add method body for burnout()
	}

	 */
	private double conditionTires(double time) {
		//TODO Add method body for conditionTires(double time)
	}

	 */
	public double race() {
		//TODO Add method body for race()
	}

	 */
	public java.lang.String toString() {
		//TODO Add method body for toString()
	}


}